# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name. Use native language.', max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='A short summary about the city with objective data.', verbose_name='Summary')),
                ('country', django_countries.fields.CountryField(help_text='Select the country in which the city is located.', max_length=2, verbose_name='Country')),
                ('coords', djgeojson.fields.PointField(help_text='Locate the city in the map.', null=True, verbose_name='Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year of this dataset.', verbose_name='Year')),
                ('population', models.PositiveIntegerField(help_text='City population.', verbose_name='Population')),
                ('city', models.ForeignKey(help_text='Select the city related to this dataset', on_delete=django.db.models.deletion.CASCADE, to='models.City', verbose_name='City')),
            ],
        ),
    ]
