# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='yeardata',
            options={'verbose_name': 'Year dataset', 'verbose_name_plural': 'Year datasets'},
        ),
        migrations.AddField(
            model_name='yeardata',
            name='source',
            field=models.CharField(help_text='Name of the source of the data provided.', max_length=128, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='yeardata',
            name='source_link',
            field=models.URLField(help_text='A link to the source data provided.', null=True, verbose_name='Source link'),
        ),
    ]
