# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20170913_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={},
        ),
    ]
