# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20170913_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='ex_compensations',
            field=models.PositiveIntegerField(default=0, verbose_name='Compensations'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ex_financial',
            field=models.PositiveIntegerField(default=0, verbose_name='Financial expenses'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ex_grants',
            field=models.PositiveIntegerField(default=0, verbose_name='Grants'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ex_material',
            field=models.PositiveIntegerField(default=0, verbose_name='Material costs'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ex_nonfinancial',
            field=models.PositiveIntegerField(default=0, verbose_name='Expenditures for the acquisition of non-financial assets'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ex_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Other expenditures'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ex_subsidies',
            field=models.PositiveIntegerField(default=0, verbose_name='Subsidies to companies'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ex_wages',
            field=models.PositiveIntegerField(default=0, verbose_name='Wages'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='in_fees',
            field=models.PositiveIntegerField(default=0, verbose_name='Revenues from fees'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='in_grants',
            field=models.PositiveIntegerField(default=0, verbose_name='Grants'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='in_nonfinancial',
            field=models.PositiveIntegerField(default=0, verbose_name='Revenues from sales of non-financial assets'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='in_penalties',
            field=models.PositiveIntegerField(default=0, verbose_name='Penalties'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='in_properties',
            field=models.PositiveIntegerField(default=0, verbose_name='Property income'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='in_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Revenues from sales of products'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='in_taxes',
            field=models.PositiveIntegerField(default=0, verbose_name='Tax revenues'),
        ),
    ]
