# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20170914_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the milestone.', max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='A short summary about the milestone.', verbose_name='Summary')),
                ('year', models.PositiveIntegerField(help_text='Year of this milestone.', verbose_name='Year')),
                ('budget', models.PositiveIntegerField(help_text='Budget allocated in this milestone.', verbose_name='Budget')),
                ('city', models.ForeignKey(help_text='Select the municipality related to this milestone', on_delete=django.db.models.deletion.CASCADE, to='models.City', verbose_name='City')),
            ],
        ),
    ]
