# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20170914_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(default='---', editable=False),
        ),
    ]
