# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 18:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_municipality_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the block.', max_length=128, verbose_name='Title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Text body of the block', verbose_name='Summary')),
            ],
        ),
    ]
