# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='image',
            field=models.ImageField(blank=True, help_text='Representative image of the municipality for the views.', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
