# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 18:48
from __future__ import unicode_literals

import apps.models.utils
import apps.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_municipality_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='image',
            field=models.ImageField(blank=True, help_text='Representative image of the municipality for the views.', null=True, upload_to=apps.models.utils.RenameImage('images/cities/'), validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Image'),
        ),
    ]
