# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20171126_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Text block', 'verbose_name_plural': 'Text blocks'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Municipality dataset', 'verbose_name_plural': 'Municipalities datasets'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'verbose_name': 'Municipality milestone', 'verbose_name_plural': 'Municipalities milestones'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Municipality basic data', 'verbose_name_plural': 'Municipalities basic data'},
        ),
    ]
