# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20171126_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='defence',
            field=models.PositiveIntegerField(default=0, verbose_name='Defence'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='economic_affaris',
            field=models.PositiveIntegerField(default=0, verbose_name='Economic affairs'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='education',
            field=models.PositiveIntegerField(default=0, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='environmental',
            field=models.PositiveIntegerField(default=0, verbose_name='Environmental protection'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='health',
            field=models.PositiveIntegerField(default=0, verbose_name='Health'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='housing',
            field=models.PositiveIntegerField(default=0, verbose_name='Housing and community ammenities'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Public order and safety'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public_services',
            field=models.PositiveIntegerField(default=0, verbose_name='General public services'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='recreation',
            field=models.PositiveIntegerField(default=0, verbose_name='Recreation, culture and religion'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='social_proctection',
            field=models.PositiveIntegerField(default=0, verbose_name='Social protection'),
        ),
    ]
