# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20171128_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='economic_affaris',
            new_name='economic_affairs',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='social_proctection',
            new_name='social_protection',
        ),
    ]
