# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20171128_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='economic_affairs',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='education',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='environmental',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_compensations',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_financial',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_grants',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_material',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_nonfinancial',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_other',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_subsidies',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ex_wages',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='health',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='in_fees',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='in_grants',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='in_nonfinancial',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='in_penalties',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='in_properties',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='in_sales',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='in_taxes',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='public_order',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='public_services',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='recreation',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='social_protection',
        ),
    ]
