# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20171204_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofogLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level', models.CharField(choices=[('PS', 'General public services'), ('DE', 'Defence'), ('PO', 'Public order and safety'), ('EA', 'Economic affairs'), ('EP', 'Environmental protection'), ('HO', 'Housing and community amenities'), ('HE', 'Health'), ('RE', 'Recreation, culture and religion'), ('ED', 'Education'), ('SP', 'Social protection')], help_text='Name of the first-level concept in the COFOG classification.', max_length=128, verbose_name='First level')),
                ('second_level', models.CharField(choices=[('0', 'Executive and legislative organs, financial and fiscal affairs, external affairs'), ('1', 'Foreign economic aid'), ('2', 'General services'), ('3', 'Basic research'), ('4', 'R&D general public services'), ('5', 'General public services n.e.c'), ('6', 'Public debt transactions'), ('7', 'Transfers of a general character between different levels of government'), ('8', 'Military defence'), ('9', 'Civil defence'), ('10', 'Foreign military aid'), ('11', 'R&D defence'), ('12', 'Defence (not classified)'), ('13', 'Police services'), ('14', 'Fire-protection services'), ('15', 'Law courts'), ('16', 'Prisons'), ('17', 'R&D public order and safety'), ('18', 'Public order and safety (not classified)'), ('19', 'General economic, commercial and labour affairs'), ('20', 'Agriculture, forestry, fishing and hunting'), ('21', 'Fuel and energy'), ('22', 'Mining, manufacturing and construction'), ('23', 'Transport'), ('24', 'Communication'), ('25', 'Other industries'), ('26', 'R&D economic affairs'), ('27', 'Economic affairs (not classified)'), ('28', 'Waste management'), ('29', 'Waste water management'), ('30', 'Pollution abatement'), ('31', 'Protection of biodiversity and landscape'), ('32', 'R&D environmental protection'), ('33', 'Environmental protection (not classified)'), ('34', 'Housing development'), ('35', 'Community development'), ('36', 'Water supply'), ('37', 'Street lighting'), ('38', 'R&D housing and community amenities'), ('39', 'Housing and community amenities (not classified)'), ('40', 'Medical products, appliances and equipment'), ('41', 'Outpatient services'), ('42', 'Hospital services'), ('43', 'Public health services'), ('44', 'R&D health'), ('45', 'Health (not classified)'), ('46', 'Recreational and sporting services'), ('47', 'Cultural services'), ('48', 'Broadcasting and publishing services'), ('49', 'Religious and other community services'), ('50', 'R&D recreation, culture and religion'), ('51', 'Recreation, culture and religion (not classified)'), ('52', 'Pre-primary and primary education'), ('53', 'Secondary education'), ('54', 'Post-secondary non-tertiary education'), ('55', 'Tertiary education'), ('56', 'Education not definable by level'), ('57', 'Subsidiary services to education'), ('58', 'R&D education'), ('59', 'Education (not classified)'), ('60', 'Sickness and disability'), ('61', 'Old age'), ('62', 'Survivors'), ('63', 'Family and children'), ('64', 'Unemployment'), ('65', 'Housing'), ('66', 'Social exclusion (not classified)'), ('67', 'R&D social protection'), ('68', 'Social protection (not classified)')], help_text='Name of the second-level concept in the COFOG classification.', max_length=128, verbose_name='Second level')),
            ],
            options={
                'verbose_name': 'COFOG level',
                'verbose_name_plural': 'COFOG levels',
            },
        ),
        migrations.CreateModel(
            name='DatasetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('dataset', models.ForeignKey(help_text='Select the dataset containing this item', on_delete=django.db.models.deletion.CASCADE, to='models.Dataset', verbose_name='Dataset')),
                ('level', models.ForeignKey(help_text='Select the name of the level in COFOG classification', on_delete=django.db.models.deletion.CASCADE, to='models.CofogLevel', verbose_name='COFOG level')),
            ],
            options={
                'verbose_name': 'Municipality dataset',
                'verbose_name_plural': 'Municipalities datasets',
            },
        ),
    ]
